[package]
name = "ut325f-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = "4.5.36"
clap_derive = "4.5.32"
tokio = { version = "1.44.2", features = ["full"]}
tokio-serial = "5.4.5"
